name: Deploy to EC2

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Install SSH Key
        uses:  shimataro/ssh-key-action@v2
        with:
         ssh-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    
      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ec2-user@ec2-3-80-141-18.compute-1.amazonaws.com 'bash /home/ec2-user/deploy.sh'
