name: Deploy to EC2

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          ssh -i /path/to/your/private-key.pem ec2-user@ec2-3-80-141-18.compute-1.amazonaws.com 'bash /home/ec2-user/deploy.sh'
